name = "EFDCLGT_LR_Runner"
uuid = "8586373c-c82d-4ad1-8f52-73ab153c2be0"
authors = ["yiyuezhuo <yiyuezhuo@gmail.com>"]
version = "0.1.2"

[deps]
EFDCLGT_LR_Files = "52cbd3d6-767d-4c35-a6ca-8d7d1225d4b0"
